name = "portfolio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[site]
bucket = "out"

# Cloudflare Pages設定
pages_build_output_dir = "out"

# MIMEタイプの設定
[[headers]]
for = "/_next/static/css/*"
[headers.values]
Content-Type = "text/css"

[[headers]]
for = "/_next/static/js/*"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/static/images/favicon.ico"
[headers.values]
Content-Type = "image/x-icon"

[env.production]
NODE_ENV = "production"
NODE_VERSION = "18.17.1"

# 環境変数の設定
[vars]
NEXT_PUBLIC_CONTACT_EMAIL = "angle.portfolio@proton.me"
NEXT_PUBLIC_CONTACT_PHONE = "090-6227-8336"
NEXT_PUBLIC_CONTACT_ADDRESS = "岩手県盛岡市津志田町二丁目8-10"

# シークレット環境変数（Cloudflareダッシュボードで設定）
# - RESEND_API_KEY 